### ISSUE TITLE
Why don't you discuss polarization

### ISSUE THREAD

**Issue by clfryer** [clfryer/MM-SNe#1]
Polarization in supernova light-curves can provide critical information of the supernova asymmetries and hence asymmetries in the supernova engine.  You have no discussion of this.  It is almost like you have something against polarization.

**Comment by nmik** [comment]
Dear Dr. Fryer,
We agree that we should add polarization as diagnostic for SNe. 
In order for your suggestion to be accounted for, pleas, submit the Google form at the link available in the README.

Regards

**Comment by nmik** [comment]
I'm closing this test-issue.
